version: "3"
services:
  webserver:
    environment:
      - MOODLE_DOCKER_DBTYPE=mysqli
      - MOODLE_DOCKER_DBCOLLATION=utf8mb4_bin
  db:
    image: mysql:5
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - ~/Workspace/data/moodle/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=m@0dl3ing
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=m@0dl3ing
      - MYSQL_DATABASE=moodle
      - character-set-server=utf8mb4
      - collation-server=utf8mb4_bin
      - innodb_file_format=barracuda
      - innodb_file_per_table=On
      - innodb_large_prefix=On
